output_dir: output/pointcloud-objaverse-cfg01

dataset:
  name: objaverse
  root_dirs:
    - /workspace/ssd2/dataset/g-bufferobjaverse/Animals/0
  view_subdir: campos_512_v4
  image_extension: .png
  pointcloud_name: pcd.npz
  points_key: points
  colours_key: colours
  num_points: 1024
  random_view: true
  image_size: 518
  cond_token_dim: 384
  cond_input_dim: 384
  seed: 0

ckpt_dir: null
batch_size: 16
num_workers: 4
seed: 0
amp: 'no'
max_grad_norm: 1.0
cfg_dropout_prob: 0.1
max_steps: 10000

image_encoder:
  model_name: dinov2_vits14

timestep_sampler:
  rate_self_consistency: 0.25
  min_dt: 0.02

logging:
  n_step_log: 50
  n_step_print: 50
  n_step_ckpt: 1000
  n_step_sample: 1000
  n_samples_per_step: 2
  steps: [1, 4]

logger:
  project_name: pointcloud-objaverse-cfg1
  run_name: debug-run
