output_dir: output/pointcloud-dummy

dataset:
  name: dummy
  num_samples: 10000
  num_points: 256
  coord_range: 1.0
  color_range: 1.0
  cond_dim: 32
  cond_length: 4
  cond_token_dim: 32
  cond_input_dim: 32
  noise_std: 0.05
  seed: 0

ckpt_dir: null
batch_size: 32
num_workers: 0
seed: 0
amp: 'no'
max_grad_norm: 1.0
cfg_dropout_prob: 0.1
max_steps: 2000
image_encoder:
  model_name: dinov2_vits14

timestep_sampler:
  rate_self_consistency: 0.25
  min_dt: 0.02

logging:
  n_step_log: 50
  n_step_print: 50
  n_step_ckpt: 500
  n_step_sample: 500
  n_samples_per_step: 2
  steps: [1, 4]

logger:
  project_name: pointcloud-dummy
  run_name: debug-run
